/*
 * Constants.h
 *
 *  Created on: Sep 20, 2023
 *      Author: FER3CLJ
 */
#ifndef INC_CONSTANTS_H_
#define INC_CONSTANTS_H_

/* GENERAL-PURPOSE CONSTANTS */

/* Application Development Stage */
#define COMDIA_PRODUCTION_STAGE 0
#define COMDIA_DEVELOPMENT_STAGE 1
#define COMDIA_TEST_STAGE 2
#define COMDIA_APP_STAGE COMDIA_DEVELOPMENT_STAGE

// General-purpose error/status flags, used primarily for ComDia_StatusFlag type
#define COMDIA_OK 1
#define COMDIA_NOT_OK 0

/* CANDRV-SPECIFIC CONSTANTS */

// Status flag for CAN initialization
#define CAN_READY COMDIA_OK
#define CAN_NOT_READY COMDIA_NOT_OK

/* In CanDrv messages not related to the modules below are discarded */
// StdId 0x000 messages are sent to CanIf by default
#define CAN_DEFAULT_STDID 0x000
#define CAN_MAX_MESSAGE_LENGTH 0x08
// StdId 0x720 messages are to be forwarded to DCM, through CanIf
#define CAN_DCM_STDID 0x720
#define CAN_DCM_RESPONSE_STDID 0x721

/* OS-SPECIFIC CONSTANTS */
// Periods of tasks
#define OS_5MS_TASK 5
#define OS_10MS_TASK 10
#define OS_1000MS_TASK 1000

/* DCM-SPECIFIC CONSTANTS */
// positive response definitions
#define DCM_POSITIVE_RESPONSE 0x00

// NRC definitions
#define DCM_NRC_SERVICE_NOT_SUPPORTED 0X11
#define DCM_NRC_SUBFUNCTION_NOT_SUPPORTED 0x12
#define DCM_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT 0x13
#define DCM_NRC_RESPONSE_TOO_LONG 0x14
#define DCM_NRC_CONDITIONS_NOT_CORRECT 0x22
#define DCM_NRC_REQUEST_SEQUENCE_ERROR 0x24
#define DCM_NRC_REQUEST_OUT_OF_RANGE 0x31
#define DCM_NRC_SECURITY_ACCESS_DENIED 0x33
#define DCM_NRC_INVALID_KEY 0x35
#define DCM_NRC_EXCEEDED_NUMBER_OF_ATTEMPTS 0x36
#define DCM_NRC_REQUIRED_TIME_DELAY_NOT_EXPIRED 0x37
#define DCM_NRC_GENERAL_PROGRAMMING_FAILURE 0x72

// Services
//service define directives
#define DCM_DID_COUNT 6
#define DCM_SERVICE_ID_DIAGNOSTIC_SESSION_CONTROL 0x10
#define DCM_SERVICE_ID_CLEAR_DIAGNOSTIC_INFORMATION 0x14
#define DCM_SERVICE_ID_READ_DTC_INFORMATION 0x19
#define DCM_SERVICE_ID_READ_DATA_BY_IDENTIFIER 0x22
#define DCM_SERVICE_ID_READ_MEMORY_BY_ADDRESS 0x23
#define DCM_SERVICE_ID_SECURITY_ACCESS 0x27
#define DCM_SERVICE_ID_WRITE_DATA_BY_IDENTIFIER 0x2E
#define DCM_SERVICE_ID_ROUTINE_CONTROL 0x31
#define DCM_SERVICE_ID_WRITE_MEMORY_BY_ADDRESS 0x3D

#define DCM_SERVICE_NRC_INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT 0x13
#define DCM_SERVICE_NRC_REQUEST_OUT_OF_RANGE 0x31
#define DCM_SERVICE_NRC_RESPONSE_TOO_LONG 0x14

//SESSIONS
#define DCM_SESSION_DEFAULT 0X01
#define DCM_SESSION_PROGRAMMING 0x02
#define DCM_SESSION_EXTENDED 0x03

/* TEST-SPECIFIC CONSTANTS */
#define COMDIA_TEST_OK COMDIA_OK
#define COMDIA_TEST_NOT_OK COMDIA_NOT_OK

#endif /* INC_CONSTANTS_H_ */
