/*
 * Responses.h
 *
 *  Created on: Sep 28, 2023
 *      Author: MNN1CLJ
 */

#ifndef INC_RESPONSES_H_
#define INC_RESPONSES_H_


//positice response define
#define POSITIVE_RESPONSE 0x00

//NRC define
#define SERVICE_NOT_SUPPORTED 0X11
#define SUBFUNCTION_NOT_SUPPORTED 0x12
#define INCORRECT_MESSAGE_LENGTH_OR_INVALID_FORMAT 0x13
#define RESPONSE_TOO_LONG 0x14
#define CONDITIONS_NOT_CORRECT 0x22
#define REQUEST_SEQUENCE_ERROR 0x24
#define REQUEST_OUT_OF_RANGE 0x31
#define SECURYTY_ACCESS_DENIED 0x33
#define INVALID_KEY 0x35
#define EXEEDED_NUMBER_OF_ATTEMPTS 0x36
#define REQUIRED_TIME_DELAY_NOT_EXPIRED 0x37
#define GENERAL_PROGRAMMING_FAILURE 0x72



#endif /* INC_RESPONSES_H_ */
